"""initial migration

Revision ID: 5ae6381bdd17
Revises: 
Create Date: 2026-04-10 23:11:15.838942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae6381bdd17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commitments', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_commitments_assigned_to_users'), 'users', ['assigned_to'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_lab_id_labs'), 'labs', ['lab_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_lab_id_labs'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'labs', ['lab_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')

    with op.batch_alter_table('commitments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_commitments_assigned_to_users'), type_='foreignkey')

    # ### end Alembic commands ###
